# PoolTool台球仿真Docker Compose配置
# 运行方法:
# cd examples/pooltool && docker compose up --build

services:
  pooltool:
    image: pooltool
    build:
      context: ../..
      dockerfile: examples/pooltool/Dockerfile
    init: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - $PWD:/app
      - ../../data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - PANDA3D_WINDOW_TYPE=${PANDA3D_WINDOW_TYPE:-offscreen}
      - LIBGL_ALWAYS_INDIRECT=1
      - MESA_GL_VERSION_OVERRIDE=3.3
    working_dir: /app/examples/pooltool
    
    # 如果有GPU可用，启用GPU支持
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # 可选：OpenPI服务器用于后续集成
  # pooltool_openpi_server:
  #   image: openpi_server
  #   build:
  #     context: ../..
  #     dockerfile: scripts/docker/serve_policy.Dockerfile
  #   init: true
  #   tty: true
  #   network_mode: host
  #   volumes:
  #     - $PWD:/app
  #     - ${OPENPI_DATA_HOME:-~/.cache/openpi}:/openpi_assets
  #   environment:
  #     - SERVER_ARGS="--env POOLTOOL"
  #     - OPENPI_DATA_HOME=/openpi_assets
  #     - IS_DOCKER=true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu] 